name: Docker Image CI

on:
#  push:
#    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
      
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: Setup Go Environment
      uses: actions/setup-go@v6.0.0
      with:
        go-version: '1.25.2'

    - name: Just for validate app build
      run: |
        cd dev/go_web_app
        go build -v ./...

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: login to registry
      uses: docker/login-action@v3.6.0
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata (tags, labels)
      id: meta
      uses: docker/metadata-action@v5
      with:
          images: denyyulianto/test-deni
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha

    - name: Build and push Docker images
      uses: docker/build-push-action@v6.18.0
      with:
          context: dev/go_web_app
          push: true
#          tags:  ${{ steps.meta.outputs.tags }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/test-deni:latest
#          labels: ${{ steps.meta.outputs.labels}}
          platforms: linux/amd64,linux/arm64
