name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: Setup Go Environment
      uses: actions/setup-go@v6.0.0
      with:
        go-version: '1.25.2'

    - name: validate app build
      run: |
        cd dev/go_web_app
        go build -v ./...

    - name: login to registry
      uses: docker/login-action@v3.6.0
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v6.18.0
      with:
          context: dev/go_web_app
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/test-deni:latest
